# Generated by Django 5.1.1 on 2024-11-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
