# Generated by Django 5.1.1 on 2024-11-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
