# Generated by Django 5.1.1 on 2024-09-29 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
