# Generated by Django 5.1.1 on 2024-10-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
