# Generated by Django 4.2.16 on 2024-12-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_videoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='duration',
            field=models.FloatField(default=10, help_text='Time played in seconds'),
            preserve_default=False,
        ),
    ]
